apiVersion: v1
kind: Secret
metadata:
  name: management-secrets
type: Opaque
stringData:
  MONGO_URL: "mongodb://hkcp_user:uB7Idr3efxqyyZED@mohe_management-database/hkcp_db"
  ADMIN_PASSWORD: "cdkwheflkwhrERSE535646"