apiVersion: apps/v1
kind: Deployment
metadata:
  name: mohe-preproduction-config-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mohe-preproduction-config-backend
  template:
    metadata:
      labels:
        app: mohe-preproduction-config-backend
    spec:
      containers:
        - name: config-backend
          image: busybox:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: mohe-preproduction-config-backend-cm
            - secretRef:
                name: mohe-preproduction-config-backend-secret