apiVersion: v1
kind: ConfigMap
metadata:
  name: mohe-preproduction-config-backend-configmap
data:
  NODE_ENV: "testing"
  MIDDLEWARE_DOMAIN: "http://middleware:3000"
  MIDDLEWARE_BASE_URL: "https://${MIDDLEWARE_DOMAIN}"
  VIRTUAL_HOST: "${CONFIGURATION_BACKEND_DOMAIN}"
  LETSENCRYPT_HOST: "${CONFIGURATION_BACKEND_DOMAIN}"
  LETSENCRYPT_EMAIL: "support@fixedmea.com"
  CORS_DOMAIN: "https://${MIDDLEWARE_DOMAIN} https://${CONFIGURATION_FRONTEND_DOMAIN} http://localhost:3010 http://localhost:3000 http://localhost:3001 http://localhost:3002 http://localhost:3003 http://localhost:3004 https://${STUDENT_INTERFACE_DOMAIN}"
  PORT: 3000