apiVersion: v1
kind: Secret
metadata:
  name: mohe-preproduction-config-backend-secret
type: Opaque
stringData:
  COOKIE_SECRET: "sa6asd$vd#1@0"
  MONGO_URL: "mongodb://moheConfigAdmin:akw$dsae78w@config-database:27017/config_db"
  REACT_APP_SERVER_DATA: |
    {
      "REACT_APP_BACKEND_URL": "https://${CONFIGURATION_BACKEND_DOMAIN}",
      "REACT_APP_SENTRY_DSN": "https://d105acdc487f4b72aa18e5579d9ebc25@bugs.fslabs.net/27",
      "REACT_APP_SENTRY_ENVIRONMENT": "testing"
    }