apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-deployment
  labels:
    app: notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
        - name: notifications
          image: busybox.yaml
          envFrom:
            - configMapRef:
                name: notifications-config
            - secretRef:
                name: notifications-secret
      restartPolicy: Always
