apiVersion: v1
kind: Secret
metadata:
  name: notifications-secret
type: Opaque
stringData:
  MONGO_URL: "mongodb://lclr_user:1th4ok1ymfurQaM9@middleware-database-0.middleware-database-headless:27017,middleware-database-1.middleware-database-headless:27017,middleware-database-2.middleware-database-headless:27017/lclr_db?replicaSet=replicaset"
  RABBITMQ_URL: "amqp://bugs-bunny:sdfjgh45iotgdfjk456@rabbitmq:5672"
