apiVersion: v1
kind: Service
metadata:
  name: notifications-service
  labels:
    app: notifications
spec:
  selector:
    app: notifications
  ports:
    - name: http
      port: 80
      targetPort: 3000  # I do not know the ports
  type: ClusterIP
