apiVersion: v1
kind: Service
metadata:
  name: agent-interface-testing-svc
  labels:
    app: agent-interface-testing
spec:
  selector:
    app: agent-interface-testing
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
