apiVersion: v1
kind: ConfigMap
metadata:
  name: employee-interface-config
data:
  EMPLOYEE_DOMAIN: ""
  MIDDLEWARE_DOMAIN: ""
  VIRTUAL_HOST: ${EMPLOYEE_DOMAIN}
  LETSENCRYPT_HOST: ${EMPLOYEE_DOMAIN}
  LETSENCRYPT_EMAIL: support@fixedmea.com
  REACT_APP_BACKEND_URL: https://${MIDDLEWARE_DOMAIN}

  NGINX_EXTRA_CONFIG: |
    add_header Content-Security-Policy "
    default-src 'self';
    font-src 'self' data: https://fonts.gstatic.com https://cdnjs.cloudflare.com;
    style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com;
    script-src 'self' https://maps.googleapis.com;
    img-src 'self' https://www.youtube.com https://maps.gstatic.com https://maps.googleapis.com data: https://${MIDDLEWARE_DOMAIN};
    connect-src 'self' https://${MIDDLEWARE_DOMAIN} https://analytics.esportal.live https://bugs.fslabs.net;
    ";
