apiVersion: v1
kind: Secret
metadata:
  name: user-interface-secret
type: Opaque
stringData:
  REACT_APP_SENTRY_DSN: "https://a9874586fb464255b574b28b2487e902@bugs.fslabs.net/29"
  REACT_APP_SERVER_DATA: |
      {
        REACT_APP_BACKEND_URL: 'https://${MIDDLEWARE_DOMAIN}',
        REACT_APP_SENTRY_DSN: 'https://a9874586fb464255b574b28b2487e902@bugs.fslabs.net/29',
        REACT_APP_SENTRY_ENVIRONMENT: 'testing'
      }