apiVersion: v1
kind: Service
metadata:
  name: user-interface-testing-svc
  labels:
    app: user-interface-testing
spec:
  selector:
    app: user-interface-testing
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
